<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class C_lap_keuangan extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        //$this->load->model('m_lap_keuangan');
        
    }

    public function index()
    {
        $this->template->load('template','v_lap_keuangan');
    }

}

/* End of file M_kegiatan.php */
/* Location: ./application/controllers/M_kegiatan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-05 20:56:11 */
/* http://harviacode.com */